services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - DEBUG=1
      - DATABASE_URL=postgresql://user:password@db:5432/school_fee_db
      - SECRET_KEY=your-secret-key-here-change-in-production
      - PYTHONUNBUFFERED=1
      - DJANGO_SETTINGS_MODULE=School.settings
    volumes:
      - .:/app
    depends_on:
      - db
    command: python manage.py runserver 0.0.0.0:8000

  db:
    image: postgres:13
    environment:
      - POSTGRES_DB=school_fee_db
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: