# Generated by Django 5.2.4 on 2025-08-20 18:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Parent', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_number', models.PositiveIntegerField(blank=True, editable=False, help_text='Auto-incremented numeric ID used internally for ordering.', null=True, unique=True)),
                ('student_id', models.CharField(blank=True, editable=False, help_text='Auto-generated student ID starting with SA (e.g., SA001).', max_length=10, null=True, unique=True)),
                ('first_name', models.CharField(help_text="Student's first name.", max_length=100, validators=[django.core.validators.MinLengthValidator(1)])),
                ('last_name', models.CharField(help_text="Student's last name.", max_length=100, validators=[django.core.validators.MinLengthValidator(1)])),
                ('current_class', models.CharField(help_text='Current academic class or grade level.', max_length=100, validators=[django.core.validators.MinLengthValidator(1)])),
                ('is_active', models.BooleanField(default=True, help_text='Indicates if the student is currently enrolled.')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the student record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the student record was last updated.')),
                ('parents', models.ManyToManyField(blank=True, help_text='Parents associated with this student.', related_name='students', to='Parent.parent')),
            ],
            options={
                'verbose_name': 'Student',
                'verbose_name_plural': 'Students',
                'ordering': ['student_number'],
                'indexes': [models.Index(fields=['student_id'], name='Student_stu_student_c66200_idx'), models.Index(fields=['student_number'], name='Student_stu_student_fd74fd_idx'), models.Index(fields=['is_active'], name='Student_stu_is_acti_2d87d5_idx'), models.Index(fields=['current_class'], name='Student_stu_current_326635_idx'), models.Index(fields=['-created_at'], name='Student_stu_created_8d6278_idx')],
                'constraints': [models.UniqueConstraint(fields=('student_number', 'student_id'), name='unique_student_number_id'), models.CheckConstraint(condition=models.Q(('first_name', ''), _negated=True), name='student_first_name_not_empty'), models.CheckConstraint(condition=models.Q(('last_name', ''), _negated=True), name='student_last_name_not_empty'), models.CheckConstraint(condition=models.Q(('current_class', ''), _negated=True), name='student_current_class_not_empty')],
            },
        ),
    ]
