# Generated by Django 5.2.4 on 2025-08-17 23:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Parent', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(blank=True, editable=False, help_text='Custom student ID starting with SA.', max_length=10, null=True, unique=True)),
                ('first_name', models.CharField(default='Unknown', help_text="Student's first name.", max_length=100)),
                ('last_name', models.CharField(default='Unknown', help_text="Student's last name.", max_length=100)),
                ('current_class', models.CharField(help_text='Current academic class or grade level.', max_length=100, validators=[django.core.validators.MinLengthValidator(1)])),
                ('is_active', models.BooleanField(default=True, help_text='Indicates if the student is currently enrolled.')),
                ('parents', models.ManyToManyField(help_text='Parents associated with this student.', related_name='students', to='Parent.parent')),
            ],
            options={
                'verbose_name': 'Student',
                'verbose_name_plural': 'Students',
                'ordering': ['student_id'],
            },
        ),
    ]
