# Generated by Django 5.2.4 on 2025-07-18 08:03

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Parent', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_class', models.CharField(help_text='Current academic class or grade level.', max_length=100, validators=[django.core.validators.MinLengthValidator(1)])),
                ('admission_date', models.DateField(default=django.utils.timezone.now, help_text='Date the student was admitted.')),
                ('is_active', models.BooleanField(default=True, help_text='Indicates if the student is currently enrolled.')),
                ('parent', models.ForeignKey(help_text='The parent responsible for this student.', on_delete=django.db.models.deletion.CASCADE, related_name='children', to='Parent.parent')),
                ('user', models.OneToOneField(help_text='Linked user account for the student.', on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Student',
                'verbose_name_plural': 'Students',
                'ordering': ['user__last_name', 'user__first_name'],
            },
        ),
    ]
