# Generated by Django 5.2.4 on 2025-07-21 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['user__email'], 'verbose_name': 'Student', 'verbose_name_plural': 'Students'},
        ),
    ]
