# Generated by Django 5.2.4 on 2025-08-18 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Parent', '0002_alter_parent_phone_number'),
        ('Student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_id',
            field=models.CharField(blank=True, editable=False, help_text='Auto-generated student ID starting with SA (e.g., SA001).', max_length=10, null=True, unique=True),
        ),
        migrations.AddConstraint(
            model_name='student',
            constraint=models.UniqueConstraint(fields=('student_number', 'student_id'), name='unique_student_number_id'),
        ),
    ]
