# Generated by Django 5.2.4 on 2025-07-27 20:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0002_alter_student_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='parent',
        ),
        migrations.AddField(
            model_name='student',
            name='parents',
            field=models.ManyToManyField(help_text='Parents responsible for this student.', related_name='students', to=settings.AUTH_USER_MODEL),
        ),
    ]
