# Generated by Django 5.2.4 on 2025-07-27 20:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0003_remove_student_parent_student_parents'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='parents',
            field=models.ManyToManyField(help_text='Parent users associated with this student.', limit_choices_to={'role': 'parent'}, related_name='linked_students', to=settings.AUTH_USER_MODEL),
        ),
    ]
