# Generated by Django 5.2.4 on 2025-07-29 21:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0004_alter_student_parents'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['first_name', 'last_name'], 'verbose_name': 'Student', 'verbose_name_plural': 'Students'},
        ),
        migrations.RemoveField(
            model_name='student',
            name='admission_date',
        ),
        migrations.RemoveField(
            model_name='student',
            name='user',
        ),
        migrations.AddField(
            model_name='student',
            name='first_name',
            field=models.CharField(default='Unknown', help_text="Student's first name.", max_length=100),
        ),
        migrations.AddField(
            model_name='student',
            name='last_name',
            field=models.CharField(default='Unknown', help_text="Student's last name.", max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='parents',
            field=models.ManyToManyField(help_text='Parents associated with this student.', limit_choices_to={'role': 'parent'}, related_name='linked_students', to=settings.AUTH_USER_MODEL),
        ),
    ]
