# Generated by Django 5.2.4 on 2025-07-29 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Parent', '0005_remove_parent_admission_date_parent_verified_and_more'),
        ('Student', '0005_alter_student_options_remove_student_admission_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='parents',
            field=models.ManyToManyField(help_text='Parents associated with this student.', related_name='students', to='Parent.parent'),
        ),
    ]
