# Generated by Django 5.2.4 on 2025-07-29 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0006_alter_student_parents'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['student_id'], 'verbose_name': 'Student', 'verbose_name_plural': 'Students'},
        ),
        migrations.AddField(
            model_name='student',
            name='student_id',
            field=models.CharField(blank=True, editable=False, help_text='Custom student ID starting with SA.', max_length=10, null=True, unique=True),
        ),
    ]
