# Generated by Django 5.2.4 on 2025-07-21 10:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Staff', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='staff',
            options={'ordering': ['user__email'], 'verbose_name': 'Staff', 'verbose_name_plural': 'Staff'},
        ),
        migrations.AlterField(
            model_name='staff',
            name='position',
            field=models.CharField(help_text='Job title or role of the staff member.', max_length=100),
        ),
        migrations.AlterField(
            model_name='staff',
            name='user',
            field=models.OneToOneField(help_text='Linked user account for the staff.', on_delete=django.db.models.deletion.CASCADE, related_name='staff_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
