# Generated by Django 5.2.4 on 2025-08-20 18:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(help_text="Parent's phone number stored in E.164 Ghana format (e.g., +233241234567).", max_length=15, unique=True, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number in E.164 Ghana format (e.g., +233241234567).', regex='^\\+233[2-9][0-9]{8}$')])),
                ('verified', models.BooleanField(default=False, help_text='Indicates if the parent has completed phone verification.')),
                ('is_primary', models.BooleanField(default=True, help_text='Indicates if this is the primary contact for students.')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Profile creation timestamp.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last update timestamp.')),
            ],
            options={
                'verbose_name': 'Parent',
                'verbose_name_plural': 'Parents',
                'ordering': ['user__first_name', 'user__last_name'],
            },
        ),
    ]
