# Generated by Django 5.2.4 on 2025-08-18 22:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Parent', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parent',
            name='phone_number',
            field=models.CharField(help_text="Parent's phone number stored in E.164 Ghana format (e.g., +233241234567).", max_length=15, unique=True, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number in E.164 Ghana format (e.g., +233241234567).', regex='^\\+233[2-9][0-9]{8}$')]),
        ),
    ]
