# Generated by Django 5.2.4 on 2025-07-21 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Parent', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='parent',
            options={'ordering': ['user__email'], 'verbose_name': 'Parent', 'verbose_name_plural': 'Parents'},
        ),
    ]
