# Generated by Django 5.2.4 on 2025-08-20 18:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Parent', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='parent',
            name='user',
            field=models.OneToOneField(help_text="Linked user account (must have role='parent').", limit_choices_to={'role': 'parent'}, on_delete=django.db.models.deletion.CASCADE, related_name='parent_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='parent',
            index=models.Index(fields=['phone_number'], name='Parent_pare_phone_n_c51d14_idx'),
        ),
        migrations.AddIndex(
            model_name='parent',
            index=models.Index(fields=['verified'], name='Parent_pare_verifie_840f6f_idx'),
        ),
        migrations.AddIndex(
            model_name='parent',
            index=models.Index(fields=['created_at'], name='Parent_pare_created_ccb3e3_idx'),
        ),
        migrations.AddIndex(
            model_name='parent',
            index=models.Index(fields=['user'], name='Parent_pare_user_id_a6ed5a_idx'),
        ),
        migrations.AddConstraint(
            model_name='parent',
            constraint=models.CheckConstraint(condition=models.Q(('phone_number', ''), _negated=True), name='parent_phone_not_empty'),
        ),
    ]
