# Generated by Django 5.2.4 on 2025-07-27 20:28

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Parent', '0002_alter_parent_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='parent',
            name='admission_date',
            field=models.DateField(default=django.utils.timezone.now, help_text='Date the parent was added to the system.'),
        ),
        migrations.AlterField(
            model_name='parent',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Timestamp when this profile was created.'),
        ),
        migrations.AlterField(
            model_name='parent',
            name='phone_number',
            field=models.CharField(help_text="Parent's phone number.", max_length=20, validators=[django.core.validators.RegexValidator(message="Phone number must be in the format: '+233123456789'. Up to 15 digits allowed.", regex='^\\+?\\d{9,15}$')]),
        ),
        migrations.AlterField(
            model_name='parent',
            name='user',
            field=models.OneToOneField(help_text="The associated user account with role='parent'.", on_delete=django.db.models.deletion.CASCADE, related_name='parent_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
