# Generated by Django 5.2.4 on 2025-08-18 22:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Parent', '0002_alter_parent_phone_number'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='parent',
            index=models.Index(fields=['user'], name='Parent_pare_user_id_a6ed5a_idx'),
        ),
    ]
