# Generated by Django 5.2.4 on 2025-08-22 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Parent', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parent',
            name='is_primary',
            field=models.BooleanField(default=True, help_text='Is this the primary contact?'),
        ),
        migrations.AlterField(
            model_name='parent',
            name='phone_number',
            field=models.CharField(help_text="Parent's phone number in local (024xxxxxxx) or E.164 Ghana format (+23324xxxxxxx).", max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='parent',
            name='verified',
            field=models.BooleanField(default=False, help_text='Phone verification status.'),
        ),
    ]
