# Generated by Django 5.2.4 on 2025-07-29 21:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Parent', '0004_alter_parent_admission_date_alter_parent_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parent',
            name='admission_date',
        ),
        migrations.AddField(
            model_name='parent',
            name='verified',
            field=models.BooleanField(default=False, help_text='Indicates if the parent has completed SMS verification.'),
        ),
        migrations.AlterField(
            model_name='parent',
            name='phone_number',
            field=models.CharField(help_text="Parent's phone number in international format.", max_length=20, validators=[django.core.validators.RegexValidator(message=' +233123456789 ', regex='^\\+?\\d{9,15}$')]),
        ),
    ]
