# Generated by Django 5.2.4 on 2025-07-29 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('parent', 'Parent'), ('admin', 'Admin')], default='parent', max_length=20),
        ),
    ]
